# CodeFemme

## Numpy

NumPy is the fundamental package for scientific computing with Python.

In Python, data is almost universally represented as NumPy arrays. Even newer tools like Pandas are built around the NumPy array.

We will be seeing: 
1. 1D array, 2D array 
2. Array slices, joins, subsets 
3. Arithmetic Operations on 2D arrays 
4. Covariance, Correlation and linear regression 


### Initializing Numpy Arrays 

1. Using np.random
2. Using np.ndarray

In [11]:
import numpy as np
np.random.seed(0)  # seed for reproducibility
x1 = np.random.randint(10, size=6)  # One-dimensional array
x2 = np.random.randint(10, size=(3, 3))  # Two-dimensional array

In [12]:
print(x1)

[5 0 3 3 7 9]


In [13]:
print(x2)

[[3 5 2]
 [4 7 6]
 [8 8 1]]


## Using np.ndarray()

In [29]:
x = np.ndarray(shape=(2,2), dtype=float,buffer = np.array([[1.1,2.2],[1.3,2.4]]))
print(x)

[[1.1 2.2]
 [1.3 2.4]]


In [25]:
x = np.ndarray(shape=(2,2), dtype=int,buffer = np.array([[1,2],[1,2]]))
print(x)

[[1.1 2.2]
 [1.3 2.4]]


## Attributes of ndarray

Each array has attributes `ndim` (the number of dimensions), `shape` (the size of each dimension), and `size` (the total size of the array):

In [14]:
print("x2.ndim = ",x2.ndim)
print("x2.shape = ",x2.shape)
print("x2.size = ",x2.size)

x2.ndim =  2
x2.shape =  (3, 3)
x2.size =  9


Another useful attribute is the `dtype` which tells you about the type of elements in the array:

In [31]:
print("x2.dtype = ",x2.dtype)

x2.dtype =  int64


Other attributes include `itemsize`, which lists the size (in bytes) of each array element, and `nbytes`, which lists the total size (in bytes) of the array:

In [37]:
print("itemsize:", x2.itemsize, "bytes")
print("nbytes:", x2.nbytes, "bytes")

itemsize: 8 bytes
nbytes: 72 bytes


## Array Indexing: Accessing Single Elements

In a one-dimensional array, the ith value (counting from zero) can be accessed by specifying the desired index in square brackets, just as with Python lists:

In [41]:
print("x1 = ",x1)
print("x1[0] = ",x1[0]) # just like arrays in c/c++
print("x1[-1] = ",x1[-1]) # negative indexing just like lists 

x1 =  [5 0 3 3 7 9]
x1[0] =  5
x1[-1] =  9


In a multi-dimensional array, items can be accessed using a comma-separated tuple of indices:

In [49]:
print("x2 = "); print(x2)
print("x2[0] = ",x2[0]) # will print the entire 1st row

# to print 1st element of 1st row
print("x2[0][0]= ", x2[0][0]) 
print("x2[0,0] = ",x2[0,0])

# to print 2nd element of 3rd row
print("x2[2][1]= ", x2[2][1])
print("x2[2,1]= ", x2[2,1])


x2 = 
[[3 5 2]
 [4 7 6]
 [8 8 1]]
x2[0] =  [3 5 2]
x2[0][0]=  3
x2[0,0] =  3
x2[2][1]=  8
x2[2,1]=  8


Values can also be modified using any of the above index notation:

In [53]:
x2[0, 0] = 12
print(x2)

[[12  5  2]
 [ 4  7  6]
 [ 8  8  1]]


In [54]:
x2[0][0] = 14
print(x2)

[[14  5  2]
 [ 4  7  6]
 [ 8  8  1]]


**NOTE :** Unlike Python lists, NumPy arrays have a fixed type. This means, for example, if you attempt to insert a floating-point value to an integer array, the value will be silently truncated.

i.e the float value gets converted to nearest int value.

In [61]:
x1 = np.ndarray(5, buffer = np.array([1,2,3,4,5]),dtype = int)
print(x1)
x1[2] = 5.7
print("x1 after changing : ",x1)

[1 2 3 4 5]
x1 after changing :  [1 2 5 4 5]


## Array Slicing and Subsetting : Accessing Subarrays

Just as we can use square brackets to access individual array elements, we can also use them to access subarrays with the slice notation, marked by the colon (:) character. The NumPy slicing syntax follows that of the standard Python list; to access a slice of an array x, use :
```python
x[start:stop:step]
```
**NOTE :** Default value of `start` is `0`, `stop` is `size of object` and `step` is `1`. 

In [71]:
x = np.ndarray(10, buffer = np.array([0,1,2,3,4,5,6,7,8,9]),dtype = int)
print(x)
print("x[:] = ",x[:])
print("x[:5] = ",x[:5])
print("x[5:] = ",x[5:])
print("x[1:5] = ",x[1:5])
print("x[1:5:2] = ",x[1:5:2])
print("x[::-1] = ",x[::-1])

[0 1 2 3 4 5 6 7 8 9]
x[:] =  [0 1 2 3 4 5 6 7 8 9]
x[:5] =  [0 1 2 3 4]
x[5:] =  [5 6 7 8 9]
x[1:5] =  [1 2 3 4]
x[1:5:2] =  [1 3]
x[::-1] =  [9 8 7 6 5 4 3 2 1 0]


In [78]:
np.random.seed(0)  # seed for reproducibility
x2 = np.random.randint(10, size=(3, 3))  
print(x2)
print("x2[:2, :3] = "); print(x2[:2, :3])  # first two rows, first three columns
print("x2[:3, ::2] = "); print(x2[:3, ::2]) # all rows, every other column
print("x2[::-1, ::-1] = "); print(x2[::-1, ::-1]) #reversed 2D array
print("x2[:, 0] = ",x2[:, 0])  # first column of x2

[[5 0 3]
 [3 7 9]
 [3 5 2]]
x2[:2, :3] = 
[[5 0 3]
 [3 7 9]]
x2[:3, ::2] = 
[[5 3]
 [3 9]
 [3 2]]
x2[::-1, ::-1] = 
[[2 5 3]
 [9 7 3]
 [3 0 5]]
x2[:, 0] =  [5 3 3]


## Joining Two Arrays

Joining of two arrays in NumPy, is primarily accomplished using the routine `np.concatenate`.

In [81]:
x = np.array([1,2,3])
y = np.array([4,5,6])
z = np.concatenate([x,y]) # Combines x and y to give one array. 
# a = np.concatenate([x,y,z])
print(z)

[1 2 3 4 5 6 1 2 3 4 5 6]


In [84]:
x2 = np.array([[1,2,3],[2,3,4]])
y2 = np.array([[3,4,5],[4,5,6]])
z2 = np.concatenate([x2,y2])
print(z2)

[[1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]]


# Arithmetic Operations on 2D arrays 

| Operator 	| Equivalent Function 	|
|----------	|---------------------	|
| +        	| np.add              	|
| -        	| np.subtract         	|
| *        	| np.multiply         	|

In [91]:
x2 = np.array([[1,2,3],[2,3,4]])
y2 = np.array([[3,4,5],[4,5,6]])
print("x2 + y2 = "); print(np.add(x2,y2))
print("x2 - y2 = "); print(np.subtract(x2,y2))
print("x2 * y2 = "); print(np.multiply(x2,y2))

x2 + y2 = 
[[ 4  6  8]
 [ 6  8 10]]
x2 - y2 = 
[[-2 -2 -2]
 [-2 -2 -2]]
x2 * y2 = 
[[ 3  8 15]
 [ 8 15 24]]
